# Generated by Django 4.2.10 on 2024-03-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'verbose_name': 'Версия', 'verbose_name_plural': 'Версии'},
        ),
        migrations.RemoveField(
            model_name='version',
            name='number',
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='version',
            name='number_version',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер версии'),
        ),
        migrations.AlterField(
            model_name='version',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активная версия'),
        ),
        migrations.AlterField(
            model_name='version',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название версии'),
        ),
    ]
