# Generated by Django 4.2.10 on 2024-03-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_version_options_remove_version_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='number_version',
            field=models.IntegerField(default=1, verbose_name='Номер версии'),
        ),
    ]
